version : '3'
services:
    app:
      container_name: docker-devconnector
      restart: always
      build: .
      ports:
        - '80:5000'
      links:
        - mongo  
    mongo:
      container_name: mongodbdevconnector
      image: mongo
      ports:
        - '27017:27017'

